# Policy
policy:
  approval:
    - or:
        - auto_approve_renovate
        - approve_by_whitelisted_user
        - approve_by_repo_writer

# Rules
approval_rules:
  - name: auto_approve_renovate
    if:
      only_has_contributors_in:
        users: [ "renovate" ]
    requires:
      count: 0
    options:
      invalidate_on_push: true
  - name: approve_by_whitelisted_user
    requires:
      count: 1
      users: 
      - osterman
      - aknysh
      - Nuru
    options:
      invalidate_on_push: true
  - name: approve_by_repo_writer
    requires:
      count: 1
      permissions: ["write"]
    options:
      invalidate_on_push: true
